
             
   P-TIMEOUT  
             



VERSION ==>                       #3.1.0

P-TIMEOUT(PROMISE, NUM            #Calls FUNC() after NUMms (using setTimeout())
 [, FUNC()|ERROR|'ERROR'])        #Def FUNC(): reject PROMISE2
 ->PROMISE2                       #  - with ERROR (def: TimeoutError with message 'Promise timed out after NUM milliseconds')
                                  #If PROMISE.cancel() is defined, fire it (see p-cancelable doc)

TimeoutError                      #
TIMEOUT_ERROR.name                #'TimeoutError'
